pub mod applications;
pub mod interface;
// pub mod app_telemetry;
// pub mod device;
// pub mod device_telemetry;
// pub mod health_check;
// pub mod input;
// pub mod operations;
// pub mod output;
// pub mod system;
// pub mod version;
// pub mod voice;
